import type { ExerciseDefinition } from "../planning/types";

export const builtInExerciseCatalog: ExerciseDefinition[] = [
  {
    id: "bodyweight-squat",
    name: "徒手深蹲",
    difficulty: "beginner",
    movement: "squat",
    requiredEquipment: [],
    measure: { kind: "reps", basis: "total" },
    goals: ["general_fitness", "strength", "hypertrophy", "endurance"],
    defaultRestSeconds: 60,
  },
  {
    id: "squat-pulse",
    name: "深蹲底部小幅起伏",
    difficulty: "intermediate",
    movement: "squat",
    requiredEquipment: [],
    measure: { kind: "reps", basis: "total" },
    goals: ["general_fitness", "hypertrophy", "endurance"],
    defaultRestSeconds: 60,
  },
  {
    id: "hip-hinge-reach",
    name: "徒手髋折叠前伸",
    difficulty: "beginner",
    movement: "hinge",
    requiredEquipment: [],
    measure: { kind: "reps", basis: "total" },
    goals: ["general_fitness", "strength", "endurance"],
    defaultRestSeconds: 45,
  },
  {
    id: "single-leg-glute-bridge",
    name: "单腿臀桥",
    difficulty: "intermediate",
    movement: "hinge",
    requiredEquipment: [],
    measure: { kind: "reps", basis: "per_side" },
    goals: ["general_fitness", "strength", "hypertrophy"],
    defaultRestSeconds: 60,
  },
  {
    id: "wall-push-up",
    name: "墙面俯卧撑",
    difficulty: "beginner",
    movement: "push",
    requiredEquipment: [],
    measure: { kind: "reps", basis: "total" },
    goals: ["general_fitness", "strength", "hypertrophy", "endurance"],
    defaultRestSeconds: 45,
  },
  {
    id: "kneeling-push-up",
    name: "跪姿俯卧撑",
    difficulty: "beginner",
    movement: "push",
    requiredEquipment: [],
    measure: { kind: "reps", basis: "total" },
    goals: ["general_fitness", "strength", "hypertrophy", "endurance"],
    defaultRestSeconds: 60,
  },
  {
    id: "strict-push-up",
    name: "标准俯卧撑",
    difficulty: "intermediate",
    movement: "push",
    requiredEquipment: [],
    measure: { kind: "reps", basis: "total" },
    goals: ["general_fitness", "strength", "hypertrophy", "endurance"],
    defaultRestSeconds: 75,
  },
  {
    id: "low-bar-inverted-row",
    name: "低杠反向划船",
    difficulty: "beginner",
    movement: "pull",
    requiredEquipment: ["pull_up_bar"],
    measure: { kind: "reps", basis: "total" },
    goals: ["general_fitness", "strength", "hypertrophy", "endurance"],
    defaultRestSeconds: 75,
  },
  {
    id: "resistance-band-row",
    name: "弹力带坐姿划船",
    difficulty: "beginner",
    movement: "pull",
    requiredEquipment: ["resistance_band"],
    measure: { kind: "reps", basis: "total" },
    goals: ["general_fitness", "strength", "hypertrophy", "endurance"],
    defaultRestSeconds: 60,
  },
  {
    id: "overhand-pull-up",
    name: "正握引体向上",
    difficulty: "intermediate",
    movement: "pull",
    requiredEquipment: ["pull_up_bar"],
    measure: { kind: "reps", basis: "total" },
    goals: ["general_fitness", "strength", "hypertrophy"],
    defaultRestSeconds: 90,
  },
  {
    id: "alternating-reverse-lunge",
    name: "交替后撤弓步",
    difficulty: "beginner",
    movement: "lunge",
    requiredEquipment: [],
    measure: { kind: "reps", basis: "per_side" },
    goals: ["general_fitness", "strength", "hypertrophy", "endurance"],
    defaultRestSeconds: 60,
  },
  {
    id: "stationary-split-squat",
    name: "原地分腿蹲",
    difficulty: "intermediate",
    movement: "lunge",
    requiredEquipment: [],
    measure: { kind: "reps", basis: "per_side" },
    goals: ["general_fitness", "strength", "hypertrophy"],
    defaultRestSeconds: 75,
  },
  {
    id: "dead-bug-reach",
    name: "死虫式交替伸展",
    difficulty: "beginner",
    movement: "core",
    requiredEquipment: [],
    measure: { kind: "reps", basis: "per_side" },
    goals: ["general_fitness", "strength", "endurance"],
    defaultRestSeconds: 45,
  },
  {
    id: "forearm-plank",
    name: "前臂平板支撑",
    difficulty: "beginner",
    movement: "core",
    requiredEquipment: [],
    measure: { kind: "durationSeconds", basis: "total" },
    goals: ["general_fitness", "strength", "endurance"],
    defaultRestSeconds: 45,
  },
  {
    id: "side-plank",
    name: "侧向平板支撑",
    difficulty: "intermediate",
    movement: "core",
    requiredEquipment: [],
    measure: { kind: "durationSeconds", basis: "per_side" },
    goals: ["general_fitness", "strength", "endurance"],
    defaultRestSeconds: 60,
  },
];
